version: '2'

services:
    app:
        image: nasajon/php:7.1-fpm-symfony-dev
        restart: always
        ports:
            - "80:80"
        volumes:
            - $PWD:/var/www/html
        env_file:
            - common.env
        networks:
            network_default:
                aliases:
                    - email_api

    postgres:
        image: postgres:11.5
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - $PWD/database/dump:/docker-entrypoint-initdb.d/
        environment:
            - "POSTGRES_DB=email"
            - "POSTGRES_USER=email"
            - "POSTGRES_PASSWORD=mysecretpassword"
        networks:
            - network_default

    rabbitmq:
        image: rabbitmq:3-management
        expose:
            - "6379"
        ports:
            - "15672:15672"
        restart: always
        environment:
            - RABBITMQ_DEFAULT_VHOST=diretorio
        networks:
            - network_default

    memcache:
        image: memcached
        restart: always
        hostname: memcache
        mem_limit: 268435456
        expose:
          - "11211"
        networks:
          - network_default
        entrypoint:
          - memcached

networks:
  network_default:
    external: true