imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-debug.log"
            level: debug
            channels: ["!event"]
        # sentry:
        #     type: service
        #     id: Sentry\Monolog\Handler
        #     level: error
        console:
            type: console
            level: info
            process_psr_3_messages: false
            channels: ["!doctrine", "!console", "!event"]
        filter_error:
            type: fingers_crossed
            action_level: error
            handler: nested_error
        nested_error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-error.log"
            level: error
        filter_info:
            type: fingers_crossed
            action_level: info
            handler: nested_info
        nested_info:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-info.log"
            level: info

web_profiler:		
    toolbar: true		
    intercept_redirects: false


doctrine_migrations:
    dir_name: "%kernel.project_dir%/database"
    namespace: DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

# sentry:
#     dsn: "https://41c8ced766e04df5ae0e9c347770785f@sentry.nasajon.com.br/60"