imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null
    #validation:
    #    cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        # sentry:
        #     type: service
        #     id: Sentry\Monolog\Handler
        #     level: error
        console:
            type: console
            level: info
            process_psr_3_messages: false
            channels: ['!doctrine', '!console', '!event']
        rabbit:
            type: amqp
            exchange: monolog_mq_channel
            exchange_name: log
            level: '%log_level%'
            process_psr_3_messages: false
            channels: '%log_channels%'

knp_gaufrette:
    adapters:
        release:
            aws_s3:
                service_id: 'aws.s3'
                bucket_name: '%env(amazon_s3_bucket_name)%'
                detect_content_type: false
                options:
                    directory: '%env(amazon_s3_bucket_path)%'
                    acl: 'public-read'
        emails_anexos:
            aws_s3:
                service_id: 'aws.s3'
                bucket_name: '%env(amazon_s3_bucket_name)%'
                detect_content_type: false
                options:
                    directory: 'emails-anexos'
                    acl: 'public-read'
    filesystems:
        release:
            adapter: release
        emails_anexos:
            adapter: emails_anexos

sentry:
    dsn: "https://3017bc8d9a1b477493ed2c9c90f5d45a:ef4cf8e537364a539b73255da98d9ae1@sentry.nasajon.com.br/8"