imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%-debug.log'
            level: debug
            channels: ['!event']
        filter_error:
            type: fingers_crossed
            action_level: error
            handler: nested_error
        nested_error:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%-error.log'
            level: error
        filter_info:
            type: fingers_crossed
            action_level: info
            handler: nested_info
        nested_info:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%-info.log'
            level: info