nasajon_login_bundle:
    resource: "@NasajonLoginBundle/Resources/config/routing.yml"

ekreative_health_check:
    resource: "@EkreativeHealthCheckBundle/Controller/"
    type:     annotation
    prefix:   /mail

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /fosrouting

app:
   resource: "routing/app.yml"

api:
   resource: "routing/api.yml"
   type: rest
   prefix: mail/v2/api
   type: rest