# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    session.memcached:
        class: Memcached
        calls:
            - [ addServer, [ "%env(memcached_host)%", "%env(memcached_port)%" ]]

    session.handler.memcached:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ '@session.memcached', { prefix: 'symfony_skeleton_sess_', expiretime: 86400 } ]


    ##Services

    Nasajon\AppBundle\NsjMail\Service\EmailsService:
        class: Nasajon\AppBundle\NsjMail\Service\EmailsService
        public: true
        arguments:
            - "@Nasajon\\AppBundle\\NsjMail\\Repository\\EmailsRepository"
            - "@Nasajon\\AppBundle\\NsjMail\\Service\\CriaEmailService"
            - "@logger"

    Nasajon\AppBundle\NsjMail\Service\CriaEmailService:
        class: Nasajon\AppBundle\NsjMail\Service\CriaEmailService
        public: true
        arguments:
            - "@bernard.producer"
            - "@gaufrette.emails_anexos_adapter"

    Nasajon\AppBundle\NsjMail\Service\EmailSmtpService:
        class: Nasajon\AppBundle\NsjMail\Service\EmailSmtpService
        public: true
        arguments:
            - "@Nasajon\\AppBundle\\NsjMail\\Repository\\EmailsSmtpRepository"
            - "@logger"
            - '%kernel.cache_dir%'
            - "@gaufrette.emails_anexos_adapter"
            - "@Nasajon\\AppBundle\\NsjMail\\Service\\PasswordService"

    Nasajon\AppBundle\NsjMail\Service\EmailSesService:
        class: Nasajon\AppBundle\NsjMail\Service\EmailSesService
        public: true
        arguments:
            - "@gaufrette.emails_anexos_adapter"
            - '@Aws\Ses\SesClient'            
            - "@logger"            
            - "%env(amazon_ses_transactional_configuration_set_name)%"

    Nasajon\AppBundle\NsjMail\Service\SendEmailService:
        class: Nasajon\AppBundle\NsjMail\Service\SendEmailService
        public: true
        arguments:
            - "@logger"
            - "@Nasajon\\AppBundle\\NsjMail\\Service\\EmailSmtpService"
            - "@Nasajon\\AppBundle\\NsjMail\\Service\\EmailSesService"

    Nasajon\AppBundle\NsjMail\Receiver\EmailReceiver:
        class: Nasajon\AppBundle\NsjMail\Receiver\EmailReceiver
        public: true
        arguments:
            - "@logger"
            - "@Nasajon\\AppBundle\\NsjMail\\Service\\SendEmailService"
            - '@doctrine'
            - "@bernard.producer"
        tags:
            - { name: bernard.receiver, message: Envio }


    bernard.serializer:
        class: Nasajon\AppBundle\NsjMail\Fila\Serializer
        public: true
        arguments:
            - "@bernard.normalizer"
            - "@jms_serializer"

    Bernard\Producer: '@bernard.producer'

    Nasajon\AppBundle\NsjMail\Service\ConfiguracaoSmtpService:
        class: Nasajon\AppBundle\NsjMail\Service\ConfiguracaoSmtpService
        public: true
        arguments:
            - "@Nasajon\\AppBundle\\NsjMail\\Repository\\ConfiguracaoSmtpRepository"
            - "@Nasajon\\AppBundle\\NsjMail\\Service\\PasswordService"

    Nasajon\AppBundle\NsjMail\Service\PasswordService:
        class: Nasajon\AppBundle\NsjMail\Service\PasswordService
        public: true
        arguments:            
            - '%env(salt)%'
            - '@logger'

    ##Repositories

    Nasajon\AppBundle\NsjMail\Repository\EmailsRepository:
        class: Nasajon\AppBundle\NsjMail\Repository\EmailsRepository
        public: true
        arguments:
            - "@doctrine.dbal.target_connection"

    Nasajon\AppBundle\NsjMail\Repository\EmailsSmtpRepository:
        class: Nasajon\AppBundle\NsjMail\Repository\EmailsSmtpRepository
        public: true
        arguments:
            - "@doctrine.dbal.default_connection"

    Nasajon\AppBundle\NsjMail\Repository\ConfiguracaoSmtpRepository:
        class: Nasajon\AppBundle\NsjMail\Repository\ConfiguracaoSmtpRepository
        public: true
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@doctrine.orm.entity_manager"